export const MENU_ITEMS = [
  { key: "home", label: "Trang chủ", pathname: "/" },
  { key: "about", label: "Giới thiệu", pathname: "/about" },
  { key: "project", label: "Dự án", pathname: "/project" },
  // { key: "blog", label: "Blog", pathname: "/blog" },
  { key: "design", label: "Quy trình thiết kế", pathname: "/design" },
  { key: "construct", label: "Quy trình thi công", pathname: "/construct" },
  { key: "contact", label: "Liên hệ", pathname: "/contact" },
];

export const SPECIALIZATION_ITEMS = [
  {
    key: "architecture",
    label: "ARCHITECTURE",
    icon: "/architecture.svg",
    content:
      "For each project we establish relationships with partners who we know will help us create added value for your project. As well as bringing together the public and private sectors, we make sector overarching links to gather knowledge and to learn from each other.",
  },
  {
    key: "interior",
    label: "INTERIOR",
    icon: "/interior.svg",
    content:
      "For each project we establish relationships with partners who we know will help us create added value for your project. As well as bringing together the public and private sectors, we make sector overarching links to gather knowledge and to learn from each other.",
  },
  {
    key: "planning",
    label: "FURNITURE",
    icon: "/planning.svg",
    content:
      "For each project we establish relationships with partners who we know will help us create added value for your project. As well as bringing together the public and private sectors, we make sector overarching links to gather knowledge and to learn from each other.",
  },
];

export const PROJECT_ITEMS = [
  {
    key: "mint-home",
    label: "MINT HOME",
    location: "Hà Nội",
    images: [
      "/images/minthome-layout.jpg",
      "/images/minthome-1.jpg",
      "/images/minthome-2.jpg",
      "/images/minthome-3.jpg",
      "/images/minthome-4.jpg",
      "/images/minthome-5.jpg",
      "/images/minthome-6.jpg",
      "/images/minthome-7.jpg",
      "/images/minthome-8.jpg",
      "/images/minthome-9.jpg",
      "/images/minthome-10.jpg",
      "/images/minthome-11.jpg",
      "/images/minthome-12.jpg",
      "/images/minthome-13.jpg",
      "/images/minthome-14.jpg",
      "/images/minthome-15.jpg",
    ],
    desc: "When you enter into any new area of science, you almost always find yourself with a baffling new language of technical terms to learn before you can converse with the experts.",
    constructionDate: new Date("2021-01-01"),
    status: "Hoàn thành",
    customer: "MintHome LTD,",
    area: "200m2",
    category: "Nhà phố",
    style: "Hiện đại",
  },
  {
    key: "mint-home-2",
    label: "MINT HOUSE",
    location: "Hồ Chí Minh",
    images: [
      "/images/minthome-layout.jpg",
      "/images/project-2.jpg",
      "/images/minthome-2.jpg",
      "/images/minthome-3.jpg",
      "/images/minthome-4.jpg",
      "/images/minthome-5.jpg",
      "/images/minthome-6.jpg",
      "/images/minthome-7.jpg",
      "/images/minthome-8.jpg",
      "/images/minthome-9.jpg",
      "/images/minthome-10.jpg",
      "/images/minthome-11.jpg",
      "/images/minthome-12.jpg",
      "/images/minthome-13.jpg",
      "/images/minthome-14.jpg",
      "/images/minthome-15.jpg",
    ],
    desc: "When you enter into any new area of science, you almost always find yourself with a baffling new language of technical terms to learn before you can converse with the experts.",
    constructionDate: new Date("2021-01-01"),
    status: "Hoàn thành",
    customer: "MintHome LTD,",
    area: "200m2",
    category: "Nhà phố",
    style: "Hiện đại",
  },
  {
    key: "beach-house",
    label: "BEACH HOUSE",
    location: "Đà Nẵng",
    images: [
      "/images/minthome-layout.jpg",
      "/images/project-3.jpg",
      "/images/minthome-2.jpg",
      "/images/minthome-3.jpg",
      "/images/minthome-4.jpg",
      "/images/minthome-5.jpg",
      "/images/minthome-6.jpg",
      "/images/minthome-7.jpg",
      "/images/minthome-8.jpg",
      "/images/minthome-9.jpg",
      "/images/minthome-10.jpg",
      "/images/minthome-11.jpg",
      "/images/minthome-12.jpg",
      "/images/minthome-13.jpg",
      "/images/minthome-14.jpg",
      "/images/minthome-15.jpg",
    ],
    desc: "When you enter into any new area of science, you almost always find yourself with a baffling new language of technical terms to learn before you can converse with the experts.",
    constructionDate: new Date("2021-01-01"),
    status: "Hoàn thành",
    customer: "MintHome LTD,",
    area: "200m2",
    category: "Nhà phố",
    style: "Hiện đại",
  },
  {
    key: "mountain-house",
    label: "MOUNTAIN HOUSE",
    location: "Sapa",
    images: [
      "/images/minthome-layout.jpg",
      "/images/project-4.jpg",
      "/images/minthome-2.jpg",
      "/images/minthome-3.jpg",
      "/images/minthome-4.jpg",
      "/images/minthome-5.jpg",
      "/images/minthome-6.jpg",
      "/images/minthome-7.jpg",
      "/images/minthome-8.jpg",
      "/images/minthome-9.jpg",
      "/images/minthome-10.jpg",
      "/images/minthome-11.jpg",
      "/images/minthome-12.jpg",
      "/images/minthome-13.jpg",
      "/images/minthome-14.jpg",
      "/images/minthome-15.jpg",
    ],
    desc: "When you enter into any new area of science, you almost always find yourself with a baffling new language of technical terms to learn before you can converse with the experts.",
    constructionDate: new Date("2021-01-01"),
    status: "Hoàn thành",
    customer: "MintHome LTD,",
    area: "200m2",
    category: "Nhà phố",
    style: "Hiện đại",
  },
];

export const ProjectItemsMap = new Map(PROJECT_ITEMS.map((item) => [item.key, item]));